
demux:
				gcc -g -Wall demux.c main.c -o demux -I/home/yy/dev/c/multimedia/ffmpeg-learning/ffmpegbuild/include -L/home/yy/dev/c/multimedia/ffmpeg-learning/ffmpegbuild/lib -lavformat -lavutil -lavcodec
				

encode_raw_yuv:
				gcc -g -Wall encode_raw_yuv.c -o encode_raw_yuv -I/home/yy/dev/c/multimedia/ffmpeg-learning/ffmpegbuild/include -L/home/yy/dev/c/multimedia/ffmpeg-learning/ffmpegbuild/lib -lavformat -lavutil -lavcodec
				
encode_raw_pcm:
				gcc -g -Wall encode_raw_pcm.c -o encode_raw_pcm -I/home/yy/dev/c/multimedia/ffmpeg-learning/ffmpegbuild/include -L/home/yy/dev/c/multimedia/ffmpeg-learning/ffmpegbuild/lib -lavformat -lavutil -lavcodec
				
ch_container:
				gcc -g -Wall ch_container.c -o ch_container -I/home/yy/dev/c/multimedia/ffmpeg-learning/ffmpegbuild/include -L/home/yy/dev/c/multimedia/ffmpeg-learning/ffmpegbuild/lib -lavformat -lavutil -lavcodec
				
transcode:
				gcc -g -Wall transcode.c main_transcode.c -o transcode -I/home/yy/dev/c/multimedia/ffmpeg-learning/ffmpegbuild/include -L/home/yy/dev/c/multimedia/ffmpeg-learning/ffmpegbuild/lib -lavformat -lavutil -lavcodec -lavfilter
				
				
demux_android:
				gcc -g -Wall demux_android.c main_demux_android.c -o demux -I/home/yy/dev/c/multimedia/ffmpeg-learning/ffmpegbuild/include -L/home/yy/dev/c/multimedia/ffmpeg-learning/ffmpegbuild/lib -lavformat -lavutil -lavcodec
				